In [13]:
# Задача 1.3.1
import numpy as np

A = np.zeros(64).reshape(8,8)
for i in range (8):
    for j in range (8):
        if (i+j)%2==0:
            A[i][j]=1

print(A)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [29]:
# Задача 1.3.2

A = np.empty((0, 0))
for i in range(5):
    A = np.append(A, np.arange(0, 5))
A = A.reshape(5, 5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
# Задача 1.3.3

A = np.random.random((3, 3, 3))
print(A)

[[[0.44554886 0.47839562 0.22427226]
  [0.23719121 0.81351889 0.09387513]
  [0.39651832 0.69772886 0.56571955]]

 [[0.16782776 0.61248006 0.47933733]
  [0.73708534 0.74365573 0.13119445]
  [0.80340245 0.40253311 0.73559268]]

 [[0.89754388 0.79229953 0.58629505]
  [0.30799345 0.34903696 0.60866725]
  [0.3654583  0.62756348 0.96709481]]]


In [31]:
# Задача 1.3.4

A = np.zeros(64).reshape(8,8)
for i in range (8):
    for j in range (8):
        if ((i==0) or (i==7) or (j==0) or (j==7)):
            A[i][j]=1
print (A)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
#Задача 1.3.5

A = np.random.random((10))
A = np.sort(A)[::-1]
print(A)

[0.99990098 0.66107307 0.64518902 0.60130694 0.39534348 0.22505152
 0.21943297 0.21327459 0.11195836 0.08909092]


In [36]:
#Задача 1.3.6

A = np.zeros(48).reshape(6,8)
print(A)
print(np.shape(A), np.size(A), np.ndim(A))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
(6, 8) 48 2


In [45]:
#Задача 2.3.1
import pandas as pd

a = pd.Series([10, 25])
b = pd.Series([80, 12])
Evk = ((b[0] - a[0])**2 + (b[1] - a[1]) ** 2)**0.5
print(Evk)

71.19691004531025


In [47]:
#Задача 2.3.2

frame = pd.read_csv('baseball.csv')
frame

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0    0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1    0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2    0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3    0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4    0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   
..     ...    ...  ...  ...  .. ..  ..  ...  ..  ...  ..  ..  ..  ..  ..  ..   
332  0.269  0.303   32   58  12  1  13   33  11   51   1   2   0   0   0   0   
333  0.288  0.366   24   47   7  0   7   24  18   23   2   3   0   0   0   0   
334  0.208  0.265   12   35  11  1   0   15  14   30   2   6   0   0   0   0   
335  0.290  0.349   59  141  30  2  16   64  42  102  14   6   1   0   0   0   
336  0.225  0.312   37   64  12  0  17   48  36   80   1   0   1   0   0   0   

     salary  
0       109  
1       160  
2      2700  
3       550  
4       300  
..      ...  
332     140  
333     525  
334     365  
335     990  
336    2167  

[337 rows x 17 columns]

In [48]:
frame.head(2)

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
0  0.271  0.328  74  161  22  6  12  58  49  133  23  17   1   1   0   0   
1  0.264  0.318  24   48   7  0   1  22  15   18   0   7   0   0   0   0   

   salary  
0     109  
1     160

In [49]:
frame.tail(3)

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
334  0.208  0.265  12   35  11  1   0  15  14   30   2   6   0   0   0   0   
335  0.290  0.349  59  141  30  2  16  64  42  102  14   6   1   0   0   0   
336  0.225  0.312  37   64  12  0  17  48  36   80   1   0   1   0   0   0   

     salary  
334     365  
335     990  
336    2167

In [50]:
frame.shape

(337, 17)

In [64]:
frame.describe()

1           2           3           4           5           6  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     0.257825    0.323973   46.697329   92.833828   16.673591    2.338279   
std      0.039546    0.047132   29.020166   51.896322   10.452001    2.543336   
min      0.063000    0.063000    0.000000    1.000000    0.000000    0.000000   
25%      0.238000    0.297000   22.000000   51.000000    9.000000    0.000000   
50%      0.260000    0.323000   41.000000   91.000000   15.000000    2.000000   
75%      0.281000    0.354000   69.000000  136.000000   23.000000    3.000000   
max      0.457000    0.486000  133.000000  216.000000   49.000000   15.000000   

                7           8           9          10          11          12  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     9.097923   44.020772   35.017804   56.706231    8.246291    6.771513   
std      9.289934   29.559406   24.842474   33.828784   11.664782    5.927490   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%      2.000000   21.000000   15.000000   31.000000    1.000000    3.000000   
50%      6.000000   39.000000   30.000000   49.000000    4.000000    5.000000   
75%     15.000000   66.000000   49.000000   78.000000   11.000000    9.000000   
max     44.000000  133.000000  138.000000  175.000000   76.000000   31.000000   

               13          14          15          16       salary  
count  337.000000  337.000000  337.000000  337.000000   337.000000  
mean     0.397626    0.115727    0.192878    0.029674  1248.528190  
std      0.490135    0.320373    0.395145    0.169938  1240.013309  
min      0.000000    0.000000    0.000000    0.000000   109.000000  
25%      0.000000    0.000000    0.000000    0.000000   230.000000  
50%      0.000000    0.000000    0.000000    0.000000   740.000000  
75%      1.000000    0.000000    0.000000    0.000000  2150.000000  
max      1.000000    1.000000    1.000000    1.000000  6100.000000

In [54]:
frame.iloc[5:8]

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
5  0.238  0.272  53  106  18  3  15  59  22  107  14   7   0   0   0   0   
6  0.115  0.148   0    3   1  0   0   2   1    6   0   3   0   0   0   0   
7  0.307  0.405  98  167  35  1  14  52  84   72   0  15   0   0   0   0   

   salary  
5     230  
6     109  
7     560

In [72]:
from sklearn import preprocessing
df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

length = list(df['sepal_length_cm'])
length = list(map(lambda x: [x], length))
length = np.array(length)

minmax = preprocessing.MinMaxScaler(feature_range = (0, 1))
minmax = minmax.fit_transform(length)
minmax

array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667],
       [0.30555556],
       [0.13888889],
       [0.13888889],
       [0.        ],
       [0.41666667],
       [0.38888889],
       [0.30555556],
       [0.22222222],
       [0.38888889],
       [0.22222222],
       [0.30555556],
       [0.22222222],
       [0.08333333],
       [0.22222222],
       [0.13888889],
       [0.19444444],
       [0.19444444],
       [0.25      ],
       [0.25      ],
       [0.11111111],
       [0.13888889],
       [0.30555556],
       [0.25      ],
       [0.33333333],
       [0.16666667],
       [0.19444444],
       [0.33333333],
       [0.16666667],
       [0.02777778],
       [0.22222222],
       [0.19444444],
       [0.05555556],
       [0.02777778],
       [0.19444444],
       [0.22222222],
       [0.13888889],
       [0.22222222],
       [0.083

In [73]:
width = list(df['sepal_width_cm'])
width = list(map(lambda x: [x], width))
width = np.array(width)

scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(width)
standard

array([[ 1.03205722],
       [-0.1249576 ],
       [ 0.33784833],
       [ 0.10644536],
       [ 1.26346019],
       [ 1.95766909],
       [ 0.80065426],
       [ 0.80065426],
       [-0.35636057],
       [ 0.10644536],
       [ 1.49486315],
       [ 0.80065426],
       [-0.1249576 ],
       [-0.1249576 ],
       [ 2.18907205],
       [ 3.11468391],
       [ 1.95766909],
       [ 1.03205722],
       [ 1.72626612],
       [ 1.72626612],
       [ 0.80065426],
       [ 1.49486315],
       [ 1.26346019],
       [ 0.56925129],
       [ 0.80065426],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [ 0.80065426],
       [ 0.33784833],
       [ 0.10644536],
       [ 0.80065426],
       [ 2.42047502],
       [ 2.65187798],
       [ 0.10644536],
       [ 0.33784833],
       [ 1.03205722],
       [ 0.10644536],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [-1.74477836],
       [ 0.33784833],
       [ 1.03205722],
       [ 1.72626612],
       [-0